name: Build

on:
  workflow_call:

jobs:
  compile:
    name: compile
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile ahk to exe
        run: |
          .\build.ps1