name: Compile AHK

on: push

jobs:
  compile:
    name: compile
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: kuzditomi/GitHub-Action-Ahk2Exe@main
        with:
          in: firefly.ahk
