name: Compile AHK

on: push

jobs:
  compile:
    name: compile
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Ahk2Exe
        uses: kuzditomi/GitHub-Action-Ahk2Exe@main
        with:
          in: firefly.ahk
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: firefly.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
