name: On push

on: push

jobs:
  onpush:
    name: On push
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile ahk to exe
        run: |
          .\build.ps1
