name: Create release

on: 
  workflow_dispatch:
    inputs:
      description:
        description: 'Release description'
        required: true
        type: string
      tagname:
        description: 'tag name'
        required: true
        type: string

jobs:
  release:
    name: Create release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile ahk to exe
        run: |
          .\build.ps1
          
      - name: Create release zip
        run: Compress-Archive -Path scripts\*.exe -CompressionLevel Optimal -DestinationPath all.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "${{ github.event.inputs.description }}"
          tag_name:  "${{ github.event.inputs.tagname }}"
          files: |
            scripts\*.exe
            all.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}