name: Create release

on:
  workflow_dispatch:
    inputs:
      description:
        description: "Release description"
        required: true
        type: string

jobs:
  release:
    name: Create release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile ahk to exe
        run: |
          .\build.ps1

      - name: Create new version number
        run: |
          .\version.ps1 "${{ github.event.inputs.description }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ github.event.inputs.description }}
          tag_name: ${{ env.NEW_VERSION }}
          files: |
            start.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Send Discord notification
        uses: tsickert/discord-webhook@v5.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          raw-data: .github/workflows/template.json
