name: Create release

on: 
  workflow_dispatch:
    inputs:
      description:
        description: 'Release description'
        required: true
        type: string
      tagname:
        description: 'tag name'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build

  release:
    runs-on: windows-latest
    needs: [build-exe-files]
    steps:
      - uses: actions/cache@v2
        id: exe-files
        with:
          path: ./scripts/*.exe
          key: ${{ github.sha }}
      
      - run: echo 'The triggering workflow passed'

      - name: create release zip
        run: Compress-Archive -Path scripts\*.exe -CompressionLevel Optimal -DestinationPath all.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "${{ github.event.inputs.description }}"
          tag_name:  "${{ github.event.inputs.tagname }}"
          files: |
            scripts\*.exe
            all.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}